Mybank/Mybank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mybank/account/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('registration', views.registration, name='registration'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('go_to_form',views.go_to_form, name='go_to_form'),
    path('account_form',views.account_form, name='account_form'),
    path('profile/<username>/',views.profile,name='profile'),
    path('update_details/<username>/',views.update_details,name='update_details'),
    path('update_password/<username>/',views.update_password,name='update_password'),
    path('delete_profile/<username>/',views.delete_profile,name='delete_profile'),
    path('expense/<username>/',views.expense,name='expense'),
    path('expense/<int:expense_id>/delete/', views.delete_expense, name='delete_expense'),
    path('update_expense/<int:expense_id>',views.update_expense,name= 'update_expense'),
]

Mybank/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

Mybank/account/models.py
from django.db import models
from django.contrib.auth.models import User

class Expense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)
    expense_date = models.DateField()
    expense_description = models.CharField(max_length=255)
    expense_amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.expense_date} - {self.expense_description} - ${self.expense_amount}"

Mybank/account/forms.py
from django import forms
from .models import Expense


class UpdateDetailsForm(forms.Form):
    username = forms.CharField(max_length=100)
    email = forms.EmailField()


class UpdatePasswordForm(forms.Form):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    repeat_password = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)



class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['expense_date', 'expense_description', 'expense_amount']

class UpdateExpense(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['expense_date', 'expense_description', 'expense_amount']

Mybank/account/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from .models import Expense
from .forms import UpdateDetailsForm,UpdatePasswordForm,ExpenseForm,UpdateExpense
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required




# Create your views here.

def registration(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        repeat_password = request.POST.get('repeat_password')

        if password == repeat_password:
            if User.objects.filter(username=username).exists():
                messages.error(request, "Username already taken")
            elif User.objects.filter(email=email).exists():
                messages.error(request, "Email already taken")
            else:
                user = User.objects.create_user(username=username, password=password, email=email)
                user.save()
                messages.success(request, "Registration successful. You can now log in.")
                return redirect('login')
        else:
            messages.error(request, "Passwords do not match")

    return render(request, "registration.html")


def login(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('go_to_form')
        else:
            messages.error(request, "Invalid username or password")

    return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')


def go_to_form(request):
    return render(request, 'go_to_form.html')


def account_form(request):
    return render(request, 'account_form.html')


def profile(request,username):
    username = User.username
    return render(request,'profile.html')


def update_details(request, username):
    user = get_object_or_404(User, username=username)

    if request.method == 'POST':
        # Handle form submission to update user details here
        # You can use Django Forms for this purpose

        form = UpdateDetailsForm(request.POST or None)
        if form.is_valid():

            new_username = form.cleaned_data['username']
            new_email = form.cleaned_data['email']

            user.username = new_username
            user.email = new_email
            user.save()

            messages.success(request, "Profile updated successfully")
            return redirect('profile', username=username)
        else:
            messages.error(request, "Error updating profile")
            return redirect('profile', username=username)

    else:
        # Create a form instance for GET requests
        form = UpdateDetailsForm()

    return render(request, 'update_details.html', {'user': user, 'form': form})
    


def update_password(request, username):
    user = get_object_or_404(User, username=username)

    if request.method == 'POST':
        # Handle form submission to update user details here
        # You can use Django Forms for this purpose

        form = UpdatePasswordForm(request.POST or None)
        if form.is_valid():
            new_password = form.cleaned_data['password']
            new_repeat_password = form.cleaned_data['repeat_password']

            if new_password == new_repeat_password:
                user.set_password(new_password)  # Update the user's password
                user.save()
                update_session_auth_hash(request, user)  # Update the session with the new password
                messages.success(request, "Password changed successfully. You can now log in.")
                return redirect('login')
            else:
                messages.error(request, "Passwords do not match")
                return redirect('profile', username=username)


        else:
            messages.error(request, "Error updating Password")
            return redirect('profile', username=username)

    else:
        # Create a form instance for GET requests
        form = UpdatePasswordForm()

    return render(request, 'update_password.html', {'user': user, 'form': form})



def delete_profile(request,username):
    if request.method == 'POST':
        user = get_object_or_404(User, username=username)
        user.delete()
        return redirect('/')
    return render(request,'delete_profile.html')

    

from django.contrib.auth.decorators import login_required

@login_required
def expense(request, username):
    user = request.user
    expenses = Expense.objects.filter(user=user).order_by('-expense_date')

    if request.method == "POST":
        form = ExpenseForm(request.POST)
        if form.is_valid():
            # Save the expense data to the database
            expense = form.save(commit=False)
            expense.user = user  # Set the user for the expense
            expense.save()
            form = ExpenseForm()  # Reset the form after saving
            messages.success(request, "Expense added successfully")
        else:
            # Debugging: Print form errors to the console
            print(form.errors)
            messages.error(request, "Error adding expense. Please check the data.")

    else:
        form = ExpenseForm()

    return render(request, 'expense.html', {'form': form, 'expenses': expenses})



@login_required
def delete_expense(request, expense_id):
    expense = get_object_or_404(Expense, id=expense_id, user=request.user)

    if request.method == 'POST':
        expense.delete()
        messages.success(request, "Expense deleted successfully")
    else:
        messages.error(request, "Invalid request")

    return redirect('expense', username=request.user.username)


@login_required
def update_expense(request, expense_id):
    expense = get_object_or_404(Expense, id=expense_id, user=request.user)

    if request.method == 'POST':
        form = UpdateExpense(request.POST, instance=expense) 
        if form.is_valid():
            form.save() 
            messages.success(request, "Expense updated successfully")
            return redirect('expense', username=request.user.username)  
        else:
            messages.error(request, "Error updating expense. Please check the data.")
    else:
        form = UpdateExpense(instance=expense)  

    return render(request, 'update_expense.html', {'form': form, 'expense': expense})

Mybank/templates/account_form.html

{% extends 'base.html' %}

{% load static %} 

{% block title %}
Open account Form

{% endblock %}


{% block content %}


<section>
  <div class="mask d-flex align-items-center h-100 gradient-custom-3 bg-secondary padding">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-4">
              <h2 class="text-uppercase text-center mb-5">Bank With Us</h2>

              <form method="post" action="#" id="registrationForm">
                {% csrf_token %}

                <div class="form-outline mb-2">
                    <label class="form-label" for="form3Example1cg">Full Name</label>
                    <input type="text" id="form3Example1cg" name="full_name" class="form-control form-control-lg"  required/>
                </div>

                <div class="form-outline mb-2">
                    <label class="form-label" for="form3Example3cg">Date Of Birth</label>
                    <input type="date"  name="dob" class="form-control form-control-lg" required />
                </div>

                <div class="form-outline mb-2">
                    <label class="form-label" >Age</label>
                    <input type="text"  name="age" class="form-control form-control-lg" required />
                </div>

                <div class="form-outline mb-2">
                    <label class="form-label" >Gender</label><br>
                    <input type="radio" class="gender-radio" name="gender" value="Male"  /> Male
                    <input type="radio" class="gender-radio" name="gender" value="Female" /> Female
                    <input type="radio" class="gender-radio" name="gender" value="Others" /> Others
                </div>

                <div class="form-outline mb-2">
                  <label class="form-label" >Phone Number</label>
                  <input type="text"  name="phone_number" class="form-control form-control-lg"  required/>
                </div>

                <div class="form-outline mb-2">
                    <label class="form-label" for="form3Example3cg">Your Email</label>
                    <input type="email" id="form3Example3cg" name="email" class="form-control form-control-lg" required />
                </div>

                <div class="form-outline mb-2">
                    <label class="form-label" for="form3Example3cg">Address</label>
                    <input type="text"  name="address" class="form-control form-control-lg" required/>
                </div>

                <div class=" category_div form-outline mb-2">
                    <label>Please specify the district:</label>
                    <select name="district" class="required-entry form-select  mb-4 mt-2" aria-label="Default select example"  onchange="javascript: dynamicdropdown(this.options[this.selectedIndex].value);">
                        <option value="">Select District</option>
                        <option value="Calicut">Calicut</option>
                        <option value="Ernakulam">Ernakulam</option>
                        <option value="Trivandrum">Trivandrum</option>
                        <option value="Coimbatore">Coimbatore</option>
                        <option value="Chennai">Chennai</option>

                    </select>
                </div>

                <div class=" category_div form-outline mb-2">
                  <label>Please specify the Branch:</label>
              </div>

              <script type="text/javascript" language="JavaScript">
                document.write('<select name="branch" id="branch" class="form-select mb-4 mt-2" aria-label="Default select example"><option value=""> select the Branch</option></select>')
              </script>
              
              <noscript>
                <select name="branch" id="branch" >
                    <option value="">Please select the Branch</option>
                </select>
              </noscript>
              


              <div class=" category_div form-outline mb-2">
                <label>Account :</label>
                <select name="account_type" class="required-entry form-select  mb-4 mt-2" aria-label="Default select example">
                    <option value="">Select Account Type</option>
                    <option value="Calicut">Saving</option>
                    <option value="Ernakulam">Current</option>
                    <option value="Trivandrum">Fixed</option>
                </select>
              </div>

              <div>
                <label style="margin-bottom: 15px;"> Materials Provided :</label><br>
                <input type="checkbox" id="debitcard" name="debitcard" value="debitcard">
                <label for="debitcard"> Debit Card</label><br>
                <input type="checkbox" id="creditcard" name="creditcard" value="creditcard">
                <label for="creditcard"> Credit Card</label><br>
                <input type="checkbox" id="chequebook" name="chequebook" value="chequebook">
                <label for="chequebook"> Cheque Book</label><br>
              </div>


              <div class="d-flex justify-content-center">
                <input  type="submit" style="margin-right: 75px;"
                    class="btn btn-success btn-block btn-lg gradient-custom-4 text-white" ></button>
                    <a href="{% url 'logout' %}">
                  <button  type="button"
                    class="btn btn-success btn-block btn-lg gradient-custom-4 text-white" >Logout</button>
                  </a>
              </div>
              

              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% block footer %}{% endblock %}  <!-- Empty footer block to hide the footer -->

<script>
  function confirmation() {
    alert("The form submission is successful");
  }
  document.getElementById("registrationForm").addEventListener("submit", function (event) {
    event.preventDefault();
    confirmation();
  });
</script>
{% endblock %}

Mybank/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'mybank-logo.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <style>
        label {
        font-weight:bold;
        }
        .gender-radio {
        margin-left:50px;
        }
        .padding {
          padding: 50px;
        }
        .image-div {
          background-size: cover;
        }
        button {
          margin-right: 25px;
          margin-left: 25px;
        }
        .delete-button{
          margin-top: 5px;
        }
        .button-update{
          margin-right: 0;
        }
        .button-delete-expense {
          margin-left: 0;
        }
    </style>

    <script language="javascript" type="text/javascript">
        var Calicut = ["Westhill","Nadakkavu","Mananchira"]
        var Ernakulam = ["Kochi","Aluva","Kakkanadu","Vyttila"]
        var Trivandrum = ["Varkkala","Museum","nemam","kovalam"]
        var Coimbatore = ["Kalapatti","Central","East","West"]
        var Chennai = ["Marina","Mylapore"]

        function dynamicdropdown(listindex) {
        var branchOptions = document.getElementById("branch");
        branchOptions.length = 0; // Clear existing options

        switch (listindex) {
            case "Calicut":
                branchOptions.options[0] = new Option("Please select branch", "");
                for (var i = 0; i < Calicut.length; i++) {
                    branchOptions.options[i + 1] = new Option(Calicut[i], Calicut[i]);
                }
                break;

            case "Ernakulam":
            branchOptions.options[0] = new Option("Please select branch", "");
                for (var i = 0; i < Ernakulam.length; i++) {
                    branchOptions.options[i + 1] = new Option(Ernakulam[i], Ernakulam[i]);
                }
                break;

            case "Trivandrum":
            branchOptions.options[0] = new Option("Please select branch", "");
                for (var i = 0; i < Trivandrum.length; i++) {
                    branchOptions.options[i + 1] = new Option(Trivandrum[i], Trivandrum[i]);
                }
                break;

            case "Coimbatore":
            branchOptions.options[0] = new Option("Please select branch", "");
                for (var i = 0; i < Coimbatore.length; i++) {
                    branchOptions.options[i + 1] = new Option(Coimbatore[i], Coimbatore[i]);
                }
                break;

            case "Chennai":
            branchOptions.options[0] = new Option("Please select branch", "");
                for (var i = 0; i < Chennai.length; i++) {
                    branchOptions.options[i + 1] = new Option(Chennai[i], Chennai[i]);
                }
                break;

            default:
                branchOptions.options[0] = new Option("Please select framework", "");
                break;
        }
        return true;
    }
</script>

</head>

<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary rounded" aria-label="Eleventh navbar example">
    <div class="container-fluid">
        <a class="navbar-brand fs-2 fw-bold" href="/">
            <img src="{% static 'mybank-logo.png' %}" height="70px" width="70px" alt="My Bank Logo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample09">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>

                {% if user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' user.username %}">{{user.username}}</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'expense' user.username %}">Expenses</a>
              </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>

                {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>

                {% endif %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">District</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" target="_blank" href="https://en.wikipedia.org/wiki/Kozhikode">Calicut</a></li>
                        <li><a class="dropdown-item" target="_blank" href="https://en.wikipedia.org/wiki/Kochi">Ernakulam</a></li>
                        <li><a class="dropdown-item" target="_blank" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">Trivandrum</a></li>
                        <li><a class="dropdown-item" target="_blank" href="https://en.wikipedia.org/wiki/Coimbatore">Coimbatore</a></li>
                        <li><a class="dropdown-item" target="_blank" href="https://en.wikipedia.org/wiki/Chennai">Chennai</a></li>
                    </ul>
                </li>
            </ul>
            <form role="search">
                <input class="form-control" type="search" placeholder="Search" aria-label="Search">
            </form>
        </div>
    </div>
</nav>


{% block content %} {% endblock %}




{% block footer %}
<div class="container">
  <footer class="py-5">
    <div class="row">
      <div class="col-6 col-md-2 mb-3">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
        </ul>
      </div>

      <div class="col-6 col-md-2 mb-3">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
        </ul>
      </div>

      <div class="col-6 col-md-2 mb-3">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
        </ul>
      </div>

      <div class="col-md-5 offset-md-1 mb-3">
        <form>
          <h5>Subscribe to our newsletter</h5>
          <p>Monthly digest of what's new and exciting from us.</p>
          <div class="d-flex flex-column flex-sm-row w-100 gap-2">
            <label for="newsletter1" class="visually-hidden">Email address</label>
            <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
            <button class="btn btn-primary" type="button">Subscribe</button>
          </div>
        </form>
      </div>
    </div>

    <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
      <p>© 2023 Company, Inc. All rights reserved.</p>
      <ul class="list-unstyled d-flex">
        <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
        <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
        <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
      </ul>
    </div>
  </footer>
</div>
{% endblock %} 

</body>
</html>

Mybank/templates/expense.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  Expense Page
{% endblock %}

{% block content %}
  <section>
    <div class="mask d-flex align-items-center h-100 gradient-custom-3 bg-secondary padding">
      <div class="container h-100">
        <div class="row">
          <div class="col-md-6">
            <div class="card" style="border-radius: 15px;">
              <div class="card-body p-5">
                <h2 class="text-uppercase text-center mb-5">Add Expense</h2>

                <form method="post">
                  {% csrf_token %}

                  <div class="form-outline mb-4">
                    <label class="form-label" for="id_expense_date">Date</label>
                    <input type="date" id="id_expense_date" name="expense_date" class="form-control form-control-lg" />
                  </div>

                  <div class="form-outline mb-4">
                    <label class="form-label" for="id_expense_description">Description</label>
                    <input type="text" id="id_expense_description" name="expense_description" class="form-control form-control-lg" />
                  </div>

                  <div class="form-outline mb-4">
                    <label class="form-label" for="id_expense_amount">Expense</label>
                    <input type="text" id="id_expense_amount" name="expense_amount" class="form-control form-control-lg" />
                  </div>

                  <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-4 text-white">Add</button>
                  </div>
                </form>
              </div>
              {% for message in messages %}
                <h3 style="text-align: center;">{{message}}</h3>
              {% endfor %}
            </div>
          </div>

          <div class="col-md-6">
            <div class="card" style="border-radius: 15px;">
              <div class="card-body p-5">
                <h2 class="text-uppercase text-center mb-5">Expense List</h2>
                {% if expenses %}
                  <ul>
                    {% for expense in expenses %}
                      <li>
                        <div class="d-flex justify-content-between align-items-center">
                          <span>{{ expense.expense_date }} - {{ expense.expense_description }} - {{ expense.expense_amount }} INR</span>
                          <form method="post" action="{% url 'update_expense' expense.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success btn-sm delete-button button-update">Update</button>
                          </form>
                          <form method="post" action="{% url 'delete_expense' expense.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm delete-button button-delete-expense" ><img src="{% static 'trash3-fill.svg' %}" alt=""></button>
                          </form>
                        </div>
                      </li>
                    {% endfor %}
                  </ul>
                {% else %}
                  <p>No expenses to display.</p>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

Mybank/templates/update_expense.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Update Expense
{% endblock %}

{% block content %}
  <section>
    <div class="mask d-flex align-items-center h-100 gradient-custom-3 bg-secondary padding">
      <div class="container h-100">
        <div class="row">
          <div class="col-md-6">
            <div class="card" style="border-radius: 15px;">
              <div class="card-body p-5">
                <h2 class="text-uppercase text-center mb-5">Update Expense</h2>

                <form method="post">
                  {% csrf_token %}

                  <div class="form-outline mb-4">
                    <label class="form-label" for="id_expense_date">Date</label>
                    <input type="date" id="id_expense_date" name="expense_date" class="form-control form-control-lg" value="{{ expense.expense_date }}" />
                  </div>

                  <div class="form-outline mb-4">
                    <label class="form-label" for="id_expense_description">Description</label>
                    <input type="text" id="id_expense_description" name="expense_description" class="form-control form-control-lg" value="{{ expense.expense_description }}" />
                  </div>

                  <div class="form-outline mb-4">
                    <label class="form-label" for="id_expense_amount">Expense</label>
                    <input type="text" id="id_expense_amount" name="expense_amount" class="form-control form-control-lg" value="{{ expense.expense_amount }}" />
                  </div>

                  <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-4 text-white">Update</button>
                  </div>
                </form>
              </div>
              {% for message in messages %}
                <h3 style="text-align: center;">{{ message }}</h3>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}